name: notes_app
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1


environment:
  sdk: ">=2.16.1 <3.0.0"



dependencies:
  flutter:
    sdk: flutter
  #flutter_quill: ^4.1.8
  floating_bottom_navigation_bar: ^1.5.2
  carousel_slider: ^4.1.1
  google_fonts: ^2.1.0
  date_time_picker: ^2.1.0
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  getwidget: ^2.0.5
  uuid: ^3.0.6
  line_icons: ^2.0.1
  provider: ^6.0.2
  intl:
  date_format:
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  hive_generator: 
    
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/user.jpg
    - assets/user2.jpg
  
